### ISSUE TITLE
WINE crash

### ISSUE THREAD

**Issue by hollunder** [pfirsich/makelove#7]
So I didn't quite remember how to run makelove and ran it without arguments in a game directory. It proceeded to try and build an AppImage and Windows executables but failed due to some issue with WINE. It seems to be using the WINE installation, which is WINE 5.5 at the moment. The problem seems to have more to do with the default prefix that makelove seems to be using. I don't usually use it myself and rather use separate prefixes using PoL or Lutris, but I can't rule out that it did exist.

```
$ ~/.local/bin/makelove
No config file found. Using default config.
Guessing project name as 'giga'
Guessed löve version from conf.lua: 0.9.1
Using default build directory 'makelove-build'
Using default love_files patterns: ['+*', '-*/.*', '-./makelove-build/*']
Building targets: win32, win64, appimage
Assembling game directory..
Warning: Pattern '*/.*' does not match any files
Warning: Pattern './makelove-build/*' does not match any files
Created makelove-build/love/giga.love
>> Building target win32
No love binaries specified for target win32
Downloading love binaries to: '/home/murks/.cache/makelove/love-binaries/0.9.1/win32'
Download complete
000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002a:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\mscoree.dll" (error=80)
002a:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\ucrtbase.dll" (error=80)
002a:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0027:fixme:service:QueryServiceConfig2W Level 6 not implemented
0027:fixme:service:QueryServiceConfig2W Level 6 not implemented
0036:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0036:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0036:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0036:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
002a:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
002a:fixme:dwmapi:DwmIsCompositionEnabled 6D95DD14
003a:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0df537, context 0x1148fd0, init_notify 0, handle 0x198fce8): stub
002a:fixme:msvcrt:__clean_type_info_names_internal (0x7a38d5c8) stub
wine: configuration in L"home/murks/.wine" has been updated.
0009:err:module:__wine_process_init L"\\\\?\\unix\\home\\murks\\.cache\\makelove\\rcedit-x64.exe" 64-bit application not supported in 32-bit prefix
Traceback (most recent call last):
  File "/home/murks/.local/bin/makelove", line 8, in <module>
    sys.exit(main())
  File "/home/murks/.local/lib/python3.8/site-packages/makelove/makelove.py", line 316, in main
    build_windows(config, version, target, target_directory, love_file_path)
  File "/home/murks/.local/lib/python3.8/site-packages/makelove/windows.py", line 202, in build_windows
    set_exe_metadata(
  File "/home/murks/.local/lib/python3.8/site-packages/makelove/windows.py", line 164, in set_exe_metadata
    sys.exit("Could not set exe metadata:\n" + res.stderr.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
0024:fixme:msvcrt:__clean_type_info_names_internal (0x64083a50) stub
```

**Comment by hollunder** [comment]
I tried again today after removing ~/.wine and it worked fine.
